[package]
name = "protohackers"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smoke-test"
path = "src/bin/smoke-test.rs"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full", "macros"] }
